name: Ubuntu 20.04 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-20_04-test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: initialize
      run: ./init.sh
      
    - name: generate-ssh
      run: ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y
      
    - name: rubyrun
      run: ruby ./init.rb
